import AquaLayout from "@/components/layouts/defaultLayout"
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App-hello",
    description: "Generated by create next app",
  };
const layout = ({children}) =>{
  
return(
<AquaLayout>{children}</AquaLayout>
)
}
export default layout