// src/head/metaData.ts
export interface Metadata {
    title: string;
    description: string;
    keywords?: string;
    author?: string;
    url?: string;
    image?: string;
  }
  
  export const defaultMetadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    keywords: "next.js, SEO, create next app",
    author: "Your Name",
    url: "https://www.yoursite.com",
    image: "https://www.yoursite.com/images/og-image.jpg",
  };
  